# 端口号
server:
  port: 7000

# 配置数据源
spring:
  application:
    name: demo-curd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:


mybatis:
  configuration:
    map-underscore-to-camel-case: true
